### ISSUE TITLE
[Bug] Donate section text appears improperly on small screens

### ISSUE THREAD

**Issue by dylansison** [deep-sea-tactics/website#14]
It was shown in the Discord server by @Daniel-Tomov that certain window dimensions push the area for ways to donate underneath the lefthand text box.

![image](https://user-images.githubusercontent.com/51481478/222035231-1fd869b5-d83f-4456-8f10-5022c5250580.png)

I have not personally tested this issue; this is solely the documentation of observation presented in the Discord server

**Comment by willuhmjs** [comment]
This issue is caused because the `max-width` property is not updated to 100% width in the media query. I will fix this in a PR.

**Comment by willuhmjs** [comment]
Fixed in #15
