### ISSUE TITLE
[Bug] Favicon has little contrast with default chromium theme

### ISSUE THREAD

**Issue by tristan-f-r** [deep-sea-tactics/website#18]
When opening the website in a standard chromium browser, the default theme does _not_ look great with the favicon:

![image depicting the favicon's whiteness - little contrast](https://user-images.githubusercontent.com/26509014/222168269-e03e6883-c91d-41bd-928e-1741ed59ecdf.png)

I'm also assuming that the same applies to firefox (both browsers have similar color themes).

**Comment by willuhmjs** [comment]
I figured this would be a problem during #6. I will recolor the logo in a future commit.

**Comment by willuhmjs** [comment]
Issue fixed by commit 61aa2da
