### ISSUE TITLE
improve padding/margins on >medium sized screens

### ISSUE THREAD

**Issue by dylansison** [deep-sea-tactics/website#19]
On small devices, thin margins are used to utilize the whole screen. Larger screens have more horizontal space and therefore can be assisted in viewability by having larger margins.

**Comment by willuhmjs** [comment]
Improvement requested by @Daniel-Tomov.

**Comment by willuhmjs** [comment]
Fixed in [e84cf28](https://github.com/deep-sea-tactics/website/commit/e84cf287a98b97a7df309322c951edfa09d9731a)
