### ISSUE TITLE
Text unnecessarily large on mobile devices

### ISSUE THREAD

**Issue by dylansison** [deep-sea-tactics/website#27]
Text is unnecessarily large when viewed on mobile, therefore difficult to read.

Can suggest completely different mobile version for website to make elements agree with phone sizing

**Comment by dylansison** [comment]
the other option would be to further split out some tabs into seperate pages such as making a mini about and adding a learn more button to go to the full description under “About”

**Comment by willuhmjs** [comment]
I do not want to split the tabs into separate pages. All sections will remain on the current page with the exception of the new LHS Sirens addition.

**Comment by willuhmjs** [comment]
@LeoDog896 What do you think about the text size on mobile devices?

**Comment by CoasterFan5** [comment]
Text size is fine on mobile.
