### ISSUE TITLE
Add page for corporate sponsorship information and contact

### ISSUE THREAD

**Issue by dylansison** [deep-sea-tactics/website#35]
Pretty much put our sponsorship information packet on a page once it gets made and completed and stuff

**Comment by CoasterFan5** [comment]
So, should we wait for the sponsorship packet to be made?

**Comment by dylansison** [comment]
> So, should we wait for the sponsorship packet to be made?

sorta, maybe when it’s like got a general idea of what to say on it (push marketing to finish it out)

**Comment by CoasterFan5** [comment]
Will follow up with marketing and add this if/when I am able to get my hands on our sponsorship packet.

**Comment by dylansison** [comment]
We have a document, it just doesn’t have anything in it. They need to give it contents and edit it is all
