### ISSUE TITLE
BREAKING CHANGE: redesign website

### ISSUE THREAD

**Issue by willuhmjs** [deep-sea-tactics/website#5]
The website could look better, so I am going to redesign it.

**Comment by tristan-f-r** [comment]
give it a go and mark @coasterfan5 a reviewer.

**Comment by tristan-f-r** [comment]
@willuhmjs can you open a draft PR so we can track it there (before that, rename it something that isn't issue 5 preferably, e.g. design since this is an internal branch?)

**Comment by willuhmjs** [comment]
@LeoDog896 yeah, no problem

**Comment by willuhmjs** [comment]
Issue resolved in #6.
