### ISSUE TITLE
team page headers don't match content or button

### ISSUE THREAD

**Issue by dylansison** [deep-sea-tactics/website#53]
![image](https://github.com/deep-sea-tactics/website/assets/51481478/26eecb09-9c77-49ab-ac2f-a773d2a3586c)

**Comment by dylansison** [comment]
![image](https://github.com/deep-sea-tactics/website/assets/51481478/0962127c-8f31-4089-8810-417e971d06ab)

**Comment by tristan-f-r** [comment]
closing in favor of #59
