### ISSUE TITLE
Update SchoolCashOnline Link

### ISSUE THREAD

**Issue by dylansison** [deep-sea-tactics/website#56]
The link is dead. See attached image for more information.

![image](https://github.com/deep-sea-tactics/website/assets/51481478/5a385080-23d8-439f-b501-c307bbe036fa)

**Comment by CoasterFan5** [comment]
It can't be fixed without a new link.

**Comment by willuhmjs** [comment]
No longer needed.

**Comment by dylansison** [comment]
I mean any way to get money for the team is worth it and likely needed; would recommend considering reimplementing this in a later iteration
