### ISSUE TITLE
[V2] Team circle button thingies cause images to be loaded when long-pressed

### ISSUE THREAD

**Issue by dylansison** [deep-sea-tactics/website#72]
unsure if this is a mobile only issue but this happens

if you hold press the buttons, it starts spinning and the photo loads in the corner but nothing else happens 

![IMG_7246](https://github.com/deep-sea-tactics/website/assets/51481478/5e811acb-464d-44cc-8623-211e7ff933cc)

**Comment by willuhmjs** [comment]
Website still in progress. Please hold your complaining until this is merged to main.
